name: mimicmotiondiffusion
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
  - pytorch3d
  - open3d-admin
dependencies:
  - gdown=4.5.1
  - h5py=3.7.0
  - joblib=1.1.0
  - matplotlib=3.4.2
  - numpy=1.21.5
  - pillow=9.2.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - spacy=3.3.1
  - tqdm=4.64.1
  - trimesh=3.15.3
  - python=3.11
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - pandas=1.3.1
  - tensorboardx=2.2
  - einops=0.3.0
  - pytorch3d=0.4.0
  - open3d=0.13.0
  - pip
  - pip:
    - diffusers==0.27.0
    - transformers==4.32.1
    - decord==0.6.0
    - einops
    - omegaconf
    - chumpy==0.70
    - smplx==0.1.28